# Generated by Django 5.0.6 on 2024-07-25 03:55

import datetime
import django.db.models.deletion
import django.utils.timezone
import management_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(max_length=100)),
                ('parkinson_diagnosis', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('care_state', models.CharField(choices=[('NOT_APPROVED', '요청 승인 대기'), ('COMPLETED', '요청 처리 완료'), ('APPROVED', '요청 승인 완료'), ('REJECT', '요청 거절')], default='NOT_APPROVED', max_length=50)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cares_approved', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'care',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='미등록', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('audio_test_result', models.CharField(default='결과 분석 중입니다.', max_length=255)),
                ('no_issue', models.BooleanField(default=False)),
                ('eye', models.BooleanField(default=False)),
                ('teeth', models.BooleanField(default=False)),
                ('skin', models.BooleanField(default=False)),
                ('back', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('other_text', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_opinion', models.TextField(blank=True, null=True)),
                ('user_request', models.TextField(blank=True, null=True)),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.care')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=management_app.models.upload_to)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='management_app.report')),
            ],
            options={
                'db_table': 'report_image',
            },
        ),
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(default=' ', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('detail_address', models.CharField(default=' ', max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(default=datetime.date(1900, 1, 1))),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('has_alzheimers', models.BooleanField(blank=True, default=False, null=True)),
                ('has_parkinsons', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='senior_photos/')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'senior',
            },
        ),
        migrations.AddField(
            model_name='care',
            name='seniors',
            field=models.ManyToManyField(related_name='cares_seniors', to='management_app.senior'),
        ),
    ]
