# Generated by Django 5.0.6 on 2024-07-25 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('care', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management_app.care')),
            ],
        ),
    ]
